//! Free monads and cofree comonads — explicit `Fix(X ↦ F(X) + Z)`.
//!
//! CDL Proposition B.18. Given an endofunctor `F`, the free monad on `F` is
//!
//! ```text
//! FreeMnd(F)(Z) = Fix(X ↦ F(X) + Z)
//! ```
//!
//! Dually, the cofree comonad on `F` is
//!
//! ```text
//! CofreeCmnd(F)(Z) = Fix(X ↦ F(X) × Z)
//! ```
//!
//! Specialisations of interest (CDL Example B.19, B.20):
//! - `FreeMnd(1 + A × −)` → `List_{−+1}(A)` (lists of `A` with last
//!   element in `Z + 1`). Concrete bijection in [`list_endo`].
//! - `FreeMnd(A + (−)²)` → `Tree(A + −)` (trees with `A + Z` labelled
//!   leaves). Concrete bijection in [`tree_endo`].
//!
//! **Why this matters for neural networks.** CDL §3.2: RNNs and recursive
//! NNs arise as **lax algebras for free parametric monads** generated by
//! parametric endofunctors. The unrolling of an RNN cell to its full
//! sequence-processing form is exactly the algebra homomorphism from the
//! initial algebra of `FreeMnd(F)` to a target F-algebra.
//!
//! ## Status
//!
//! Recursive bodies present. The two carriers
//!
//! - [`FreeMnd<F, Z>`] — the inductive enum `Pure | Roll`.
//! - [`CofreeCmnd<F, Z>`] — the recursive record `(head, tail)`.
//!
//! are parameterised by an [`HKT`] witness whose object map is the GAT
//! [`HKT::Type`] (with morphism map [`Functor::fmap`]). Concrete instances
//! and their iso witnesses:
//!
//! - [`list_endo::ListEndo<A>`] / [`list_endo::free_mnd_to_vec`] /
//!   [`list_endo::vec_to_free_mnd`].
//! - [`tree_endo::TreeEndo<A>`] / [`tree_endo::BinaryTree<A>`] /
//!   [`tree_endo::tree_to_free_mnd`] / [`tree_endo::free_mnd_to_tree`].
//!
//! The bijection helpers are *not* re-exported at the crate root — keep
//! the qualified path `catgraph_dl::free_monad::list_endo::*` and
//! `catgraph_dl::free_monad::tree_endo::*` for downstream consumers, so the
//! crate root surface stays focused on the categorical primitives.
//!
//! ## Outstanding work
//!
//! The free-monad-side algebra-homomorphism unroller (CDL Remark 2.13 —
//! `foldr`/`foldl` recovered as the unique algebra hom from the initial
//! algebra of `FreeMnd(1 + A × −)`) is deferred; it would consume the
//! [`HKT`]/[`Functor`] witnesses alongside the F-algebra body.

pub mod cofree_cmnd;
pub mod free_mnd;
pub mod list_endo;
pub mod tree_endo;

// The endofunctor witnesses are the `deep_causality_haft` `HKT` / `Functor`
// traits, re-exported through `crate::endofunctor` (issue #12). Surfaced here
// so `catgraph_dl::free_monad::{HKT, Functor}` resolves for the recursive
// carriers below.
pub use crate::endofunctor::{EndoWitness, Functor, HKT};
pub use cofree_cmnd::CofreeCmnd;
pub use free_mnd::FreeMnd;
