//! Free monads and cofree comonads — explicit `Fix(X ↦ F(X) + Z)`.
//!
//! CDL Proposition B.18. Given an endofunctor `F`, the free monad on `F` is
//!
//! ```text
//! FreeMnd(F)(Z) = Fix(X ↦ F(X) + Z)
//! ```
//!
//! Dually, the cofree comonad on `F` is
//!
//! ```text
//! CofreeCmnd(F)(Z) = Fix(X ↦ F(X) × Z)
//! ```
//!
//! Specialisations of interest (CDL Example B.19, B.20):
//! - `FreeMnd(1 + A × −)` → `List_{−+1}(A)` (lists of `A` with last
//!   element in `Z + 1`). Concrete bijection in [`list_endo`].
//! - `FreeMnd(A + (−)²)` → `Tree(A + −)` (trees with `A + Z` labelled
//!   leaves). Concrete bijection in [`tree_endo`].
//!
//! **Why this matters for neural networks.** CDL §3.2: RNNs and recursive
//! NNs arise as **lax algebras for free parametric monads** generated by
//! parametric endofunctors. The unrolling of an RNN cell to its full
//! sequence-processing form is exactly the algebra homomorphism from the
//! initial algebra of `FreeMnd(F)` to a target F-algebra.
//!
//! ## Status
//!
//! Recursive bodies present. The two carriers
//!
//! - [`FreeMnd<F, Z>`] — the inductive enum `Pure | Roll`.
//! - [`CofreeCmnd<F, Z>`] — the recursive record `(head, tail)`.
//!
//! are parameterised by an [`HKT`] witness whose object map is the GAT
//! [`HKT::Type`] (with morphism map [`Functor::fmap`]). Concrete instances
//! and their iso witnesses:
//!
//! - [`list_endo::ListEndo<A>`] / [`list_endo::free_mnd_to_vec`] /
//!   [`list_endo::vec_to_free_mnd`].
//! - [`tree_endo::TreeEndo<A>`] / [`tree_endo::BinaryTree<A>`] /
//!   [`tree_endo::tree_to_free_mnd`] / [`tree_endo::free_mnd_to_tree`].
//!
//! The bijection helpers are *not* re-exported at the crate root — keep
//! the qualified path `catgraph_dl::free_monad::list_endo::*` and
//! `catgraph_dl::free_monad::tree_endo::*` for downstream consumers, so the
//! crate root surface stays focused on the categorical primitives.
//!
//! ## Relationship to haft 0.4.0's `Free` / `FreeWitness` (#76)
//!
//! haft 0.4.0 newly ships a crate-root free monad — `Free<F, A>` (`Pure |
//! Suspend`, `alloc`-gated) + `FreeWitness` — structurally the same
//! free-monad-over-endofunctor construction as [`FreeMnd`]. Under #12's "adopt
//! haft witnesses, drop hand-rolled equivalents" principle this looks like a
//! duplication to collapse. It is **deliberately not collapsed** (decision
//! recorded on [#76](https://github.com/sustia-llc/catgraph/issues/76));
//! [`FreeMnd`] / [`CofreeCmnd`] stay native. Why:
//!
//! 1. **Equality.** haft's `Free` ships *no* `Clone`/`Debug`/`PartialEq`/`Eq`
//!    (it is "compared by folding"). [`CofreeCmnd`]'s structural equality is
//!    exercised directly (`tests/free_monad_bijections.rs::cofree_cmnd_smoke`
//!    asserts `==`), and [`FreeMnd`] carries the matching manual impls for
//!    symmetry — adopting `Free` would forfeit both.
//! 2. **No cofree twin.** haft has no `CofreeCmnd` counterpart. Adopting `Free`
//!    for the monad side alone would split the matched CDL Prop-B.18 (co)algebra
//!    pair that this module is built around.
//! 3. **Minimal carrier.** [`FreeMnd`]/[`CofreeCmnd`] are deliberately minimal
//!    inductive carriers (`pure`/`roll`/`new`) anchored to CDL Prop B.18; haft's
//!    `Free`/`FreeWitness` carry an algebraic-effects `bind`/`map`/`fold`/`lift`
//!    surface these carriers do not need.
//!
//! The seam ([`crate::endofunctor`]) therefore does **not** re-export haft's
//! `Free`; the two coexist by design, not by oversight.
//!
//! ## Outstanding work
//!
//! The free-monad-side algebra-homomorphism unroller (CDL Remark 2.13 —
//! `foldr`/`foldl` recovered as the unique algebra hom from the initial
//! algebra of `FreeMnd(1 + A × −)`) is deferred; it would consume the
//! [`HKT`]/[`Functor`] witnesses alongside the F-algebra body.

pub mod cofree_cmnd;
pub mod free_mnd;
pub mod list_endo;
pub mod tree_endo;

// The endofunctor witnesses are the `deep_causality_haft` `HKT` / `Functor`
// traits, re-exported through `crate::endofunctor` (issue #12). Surfaced here
// so `catgraph_dl::free_monad::{HKT, Functor}` resolves for the recursive
// carriers below.
pub use crate::endofunctor::{EndoWitness, Functor, HKT};
pub use cofree_cmnd::CofreeCmnd;
pub use free_mnd::FreeMnd;
